// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Initialize() {
  return window['go']['main']['App']['Initialize']();
}

export function Prompt(arg1) {
  return window['go']['main']['App']['Prompt'](arg1);
}
